name: adeyemi-portfolio
owner: folarinabdul30

# Use the local project in ./web as the app source (Next.js)
package: .
kind: nextjs
dir: web

env:
  NODE_ENV: production

build:
  command: pnpm install && pnpm build

start:
  command: pnpm start -p $PORT
