[package]
name = "adeyemi-portfolio"
version = "0.1.0"

# Basic Wasmer Edge config for a Next.js app located in ./web
[app]
kind = "nextjs"
dir = "web"

[app.env]
NODE_ENV = "production"

# Secrets to set in Wasmer (dashboard or CLI):
# DATABASE_URL, RESEND_API_KEY, RESEND_TO, RESEND_FROM, NEXT_PUBLIC_SITE_URL

[app.build]
command = "pnpm install && pnpm build"

[app.start]
command = "pnpm start -p $PORT"
